name: Operation Test

on:
  push:
    branches:
      - dev
jobs:
  download:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y chromium-browser chromium-chromedriver

      - name: Run webpicget
        run: ./dist/webpicget https://k310.netlify.app/other/webpicget%E3%81%AE%E3%83%86%E3%82%B9%E3%83%88%E7%94%A8%E3%83%9A%E3%83%BC%E3%82%B8 pictures

      - name: images
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-images
          path: pictures/
